<?php return array(
    'root' => array(
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'reference' => NULL,
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'reference' => NULL,
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.14.0',
            'version' => '4.14.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '12ab42bd6e742c70c0a52f7b82477fcd44e64b75',
            'dev_requirement' => false,
        ),
        'fakerphp/faker' => array(
            'pretty_version' => 'v1.19.0',
            'version' => '1.19.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fakerphp/faker',
            'aliases' => array(),
            'reference' => 'd7f08a622b3346766325488aa32ddc93ccdecc75',
            'dev_requirement' => false,
        ),
        'maennchen/zipstream-php' => array(
            'pretty_version' => '2.2.1',
            'version' => '2.2.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maennchen/zipstream-php',
            'aliases' => array(),
            'reference' => '211e9ba1530ea5260b45d90c9ea252f56ec52729',
            'dev_requirement' => false,
        ),
        'markbaker/complex' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/complex',
            'aliases' => array(),
            'reference' => 'ab8bc271e404909db09ff2d5ffa1e538085c0f22',
            'dev_requirement' => false,
        ),
        'markbaker/matrix' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../markbaker/matrix',
            'aliases' => array(),
            'reference' => 'c66aefcafb4f6c269510e9ac46b82619a904c576',
            'dev_requirement' => false,
        ),
        'myclabs/php-enum' => array(
            'pretty_version' => '1.8.3',
            'version' => '1.8.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/php-enum',
            'aliases' => array(),
            'reference' => 'b942d263c641ddb5190929ff840c68f78713e937',
            'dev_requirement' => false,
        ),
        'phpoffice/phpspreadsheet' => array(
            'pretty_version' => '1.23.0',
            'version' => '1.23.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpspreadsheet',
            'aliases' => array(),
            'reference' => '21e4cf62699eebf007db28775f7d1554e612ed9e',
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'dev_requirement' => false,
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'reference' => '2dfb5f6c5eff0e91e20e913f8c5452ed95b86621',
            'dev_requirement' => false,
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'reference' => '12ac7fcd07e5b077433f5f2bee95b3a771bf61be',
            'dev_requirement' => false,
        ),
        'psr/http-message' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'reference' => 'f6561bf28d520154e4b0ec72be95418abe6d9363',
            'dev_requirement' => false,
        ),
        'psr/simple-cache' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/simple-cache',
            'aliases' => array(),
            'reference' => '408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
            'dev_requirement' => false,
        ),
        'simitgroup/phpjasperxml' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../simitgroup/phpjasperxml',
            'aliases' => array(),
            'reference' => 'e6cf1dea3077594d14687bc5cedb90bd31d6673a',
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.2',
            'version' => '2.5.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'reference' => 'e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.26.0',
            'version' => '1.26.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'reference' => '9344f9cb97f3b19424af1a21a3b0e75b0a7d8d7e',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-barcode' => array(
            'pretty_version' => '1.17.14',
            'version' => '1.17.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-barcode',
            'aliases' => array(),
            'reference' => '4907ef1e384dbb7d3100c897925e7dc071a419a3',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-color' => array(
            'pretty_version' => '1.14.14',
            'version' => '1.14.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-color',
            'aliases' => array(),
            'reference' => 'f9e45c59496418227184626ad31e83470153c11f',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-file' => array(
            'pretty_version' => '1.7.14',
            'version' => '1.7.14.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-file',
            'aliases' => array(),
            'reference' => 'aa03fcc70873a620cc2ebcd351bbb005830c338d',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf' => array(
            'pretty_version' => '8.0.10',
            'version' => '8.0.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf',
            'aliases' => array(),
            'reference' => '695646bfba4c11578e9316c6f57b4cb59e13b9b1',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-encrypt' => array(
            'pretty_version' => '1.6.10',
            'version' => '1.6.10.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-encrypt',
            'aliases' => array(),
            'reference' => '6c9f137c112607d8358f35939e8c495e9d56380a',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-font' => array(
            'pretty_version' => '1.9.7',
            'version' => '1.9.7.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-font',
            'aliases' => array(),
            'reference' => '7766e3917157c22204493232119ee3130c0681ff',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-graph' => array(
            'pretty_version' => '1.5.8',
            'version' => '1.5.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-graph',
            'aliases' => array(),
            'reference' => '6a622030b23b5354534a6d37d35f1daba5b087c0',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-image' => array(
            'pretty_version' => '1.3.9',
            'version' => '1.3.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-image',
            'aliases' => array(),
            'reference' => '298850c716dbc8d567c4b17c2d01d642ef8ad157',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-pdf-page' => array(
            'pretty_version' => '2.5.8',
            'version' => '2.5.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-pdf-page',
            'aliases' => array(),
            'reference' => 'f24f78baf2048450684ce4c120439e6e3f30fb54',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-unicode' => array(
            'pretty_version' => '1.4.9',
            'version' => '1.4.9.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-unicode',
            'aliases' => array(),
            'reference' => 'd032df898643379ee5bfaa45162fb02defaf16b8',
            'dev_requirement' => false,
        ),
        'tecnickcom/tc-lib-unicode-data' => array(
            'pretty_version' => '1.7.8',
            'version' => '1.7.8.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tc-lib-unicode-data',
            'aliases' => array(),
            'reference' => '806a3fcd81389be8bf271244c6ac9b541b6fddb1',
            'dev_requirement' => false,
        ),
        'tecnickcom/tcpdf' => array(
            'pretty_version' => '6.4.4',
            'version' => '6.4.4.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnickcom/tcpdf',
            'aliases' => array(),
            'reference' => '42cd0f9786af7e5db4fcedaa66f717b0d0032320',
            'dev_requirement' => false,
        ),
    ),
);
